#!/bin/bash
set -e

# Add /usr/bin/ link
ln -s /opt/ftprog2/ftprog2 /usr/bin/ftprog2 2>/dev/null || true

# Update man pages
mandb -q

# Just loading to suppress warning
. /usr/share/debconf/confmodule || true

# Done
exit 0
