#!/bin/bash
set -e

# Add /usr/bin/ link
ln -s /opt/altftprog/altftprog /usr/bin/altftprog 2>/dev/null || true

# Update man pages
mandb -q

# Just loading to suppress warning
. /usr/share/debconf/confmodule || true

# Done
exit 0
