#!/bin/bash
set -e

# Kill application
PID=$(ps aux | grep '[/]opt/ftprog2/ftprog2' | awk '{print $2}')
if [[ $PID != "" ]]; then
    sudo kill $PID 2>/dev/null || true
fi

# Remove /usr/bin/ link
rm /usr/bin/ftprog2 || true

# Done
exit 0
